title: Minsoo9506's blog
description: Study blog

url: https://minsoo9506.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 7

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Category
    url: /contact

social:
  github: minsoo9506
  #twitter: brianmaierjr
  #facebook: brianmaierjr
  email: ghktjd15gh@gmail.com
  #linkedin: brianmaierjr

google_analytics: "UA-58263416-1"

disqus:
    shortname: minsoo9506